### ISSUE TITLE
Corrections while proning

### ISSUE THREAD

**Issue by primody** [Vaei/PredictedMovementExample#4] opened 2023-09-04 21:30 UTC
If I clone down the package without modifying anything then go straight to 2 player listen server I see corrections on client while walking and proning.

**Comment by Vaei** [comment] 2023-09-04 21:55
I cannot reproduce this. I am unable to see any corrections despite simulating >200ms latency and with `p.netshowcorrections 1` set. With 2 clients + 1 listen server, no one encounters any corrections while walking around in prone (even when coming in and out of prone). More detailed information is needed.

**Comment by primody** [comment] 2023-09-04 22:16
I am grabbing a video. What I do is hold down "W" to walk and then just spam "Z" to try and prone and stand as fast as possible.

**Comment by primody** [comment] 2023-09-04 22:19
https://github.com/Vaei/PredictedMovementExample/assets/49540168/fc17712f-ded7-43f7-be5a-c17fcce2768e

This is with 0 packet lag. I cloned this project, opened the ".uproject" file. Asked to build the projects and I selected yes. Then went straight into testing it. I am using UE Version 5.1.1

**Comment by Vaei** [comment] 2023-09-04 23:19
Thanks for the information. I have reproduced the issue and can confirm it exists. The issue is caused by the way I implemented the prone lock timer. Setting it to 0.0 to disable it "fixes" it in the meantime. I will fix this in the hopefully near future, feel free to bug me later if I forget.

**Comment by primody** [comment] 2023-09-04 23:37
Ah ok interesting. I will keep an eye out for any pushes. I am still learning right now so not sure if I would actually be able to use this but it is very interesting to compare to another approach someone did. Thanks!

**Comment by Vaei** [comment] 2023-09-15 22:30
Fixed in PredictedMovement version 1.0.2.0. Relevant commit: https://github.com/Vaei/PredictedMovement/commit/647e09807ca602fcf0b4086d21992ca794806e5e

Thanks for taking the time to report this :)

You can get the changes by using the instructions here: https://github.com/Vaei/PredictedMovementExample#updating-repo

**Closed as completed by Vaei** 2023-09-15 22:30 UTC
